---
- include: lamp-centos.yml
  when:
    - ansible_distribution == "CentOS" or
    - ansible_distribution == "Red Hat Enterprise Linux"
  static: no

- include: lamp-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"
  static: no

- include: lamp-debian.yml
  when:
    - ansible_distribution == "Debian"
  static: no
