---

# This is for the entire site.yml

- hosts: servers
  become: true
  roles:
    - common
    - database
    - web

#- hosts: web-servers
#  become: true
#  roles:
#    - common
#    - web

#- hosts: database-servers
#  become: true
#  roles:
#    - common
#    - database
