---
#- name: Run Windows playbook against Windows hosts
#  hosts: windows
#  become: yes
#  roles:
#    - windows-servers
#    - windows-workstations

- name: Run Linux playbook against Linux hosts
  hosts: linux-servers
  become: yes
  roles:
    - linux

#- name: Run Unix playbook against Unix hosts
#  hosts: unix-servers
#  become: yes
#  roles:
#    - unix

#- name: Run VMWare playbook against Virtual Machines (VM)
#  hosts: vmware
#  become: yes
#  roles:
#    - esxi-host
