---

- name: Install required packaged for Active Directory integration.
  yum:
    name:
      - adcli
      - sssd
      - authconfig
      - krb5-workstation
      - expect
    state: present

- name: Install pexpect module.
  pip:
    name: pexpect
    executable: pip3

- name: Deploy krb5.conf template.
  template:
    src: roles/rhel_ad/templates/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Join Active Directory domain.
  shell: |
    adcli join {{ fqdn }} -U {{ ad_user }}
    expect "Password for {{ ad_user }}\@{{ fqdn }}:"
    send "{{ ad_pass }}"
    args:
      executable: /usr/bin/expect

        #- name: Join Active Directory domain
        #shell: |
          #realm join --user={{ ad_user}} {{ fqdn }}
          #expect "Password for {{ ad_user }}:"
          #send "{{ ad_pass }}"
          #args:
            #executable: /usr/bin/expect

- name: Execute authconfig to configure Name Service Switch (NSS) and PAM stack.
  shell:
    cmd: authconfig --enablesssd --enablesssdauth --enablelocauthorize --enablemkhomedir --update

- name: Deploy sssd.conf template.
  template:
    src: roles/rhel_ad/templates/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    #mode: 0600
    mode: 600
    backup: yes

- name: Start and enable sssd service
  systemd:
      name: sssd
      state: started
      enabled: yes



