---

- name: Install required packaged for Active Directory integration.
  yum:
    name:
      - adcli
      - sssd
      - authconfig
      - krb5-workstation
      - expect
    state: present

- name: Install pexpect module.
  pip:
    name: pexpect
    executable: pip3

- name: Deploy krb5.conf template.
  template:
    src: roles/rhel_ad/templates/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Check to see if system is already joined to domain
  command: /bin/bash -c "/usr/sbin/realm list"
  register: realm_list_results

- name: Join Active Directory domain
  shell: "echo {{ ad_pass }} | realm join --user={{ ad_user }} --computer-ou={{ ad_ou }} --unattended {{ fqdn }}"
  when: realm_list_results.stdout == ""
  tags: ad

- name: Execute authconfig to configure Name Service Switch (NSS) and PAM stack.
  shell:
    cmd: authconfig --enablesssd --enablesssdauth --enablelocauthorize --enablemkhomedir --update
  tags: ad

- name: Deploy sssd.conf template.
  template:
    src: roles/rhel_ad/templates/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    #mode: 0600
    mode: 0644
    backup: yes

- name: Start and enable sssd service
  systemd:
      name: sssd
      state: started
      enabled: yes



