---
# tasks file for web-servers

- name: Install web server packages
  yum: name={{ item }} state=latest
  with_items:
    - httpd
    - php
    - php-mysql

- name: Install PHP info page
  template:
      src: ../templates/index.php.j2
      dest: /var/www/html/index.php

- name: start and enable httpd
  service:
    name: httpd
    enabled: yes
    state: started