---
- name: Add HTTP services to firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Add HTTPS services to firewalld
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true

- name: Add SSH to firewalld
  firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true

- name: Add MariaDB port to firewalld
  firewalld:
    service: mysql
    permanent: true
    state: enabled
    immediate: true
