---
# tasks file for common

- name: Install EPEL repo
  yum: name=epel-release state=present

- name: Install common dependencies
  yum: name={{ item }} state=latest
  with_items:
    - libselinux-python
    - libsemanage-python
    - firewalld

- include_tasks: selinux.yml
- include_tasks: firewalld.yml
- include_tasks: ntp.yml
- include_tasks: motd.yml
