---
# tasks file for spacewalk-server

- name: Install EPEL repository
  yum:
    name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state=present

- name: Install Spacewalk repository
  yum:
    name: http://yum.spacewalkproject.org/2.7/RHEL/7/x86_64/spacewalk-repo-2.7-2.el7.noarch.rpm
    state: present

- name: Install Java 7 repository
  get_url:
    url: "{{ java_repo }}"
    dest: /etc/yum.repos.d
#  include_vars:
#    file: ../vars/main.yml

- name: Install Spacewalk-Setup-Postgresql
  yum:
    name=spacewalk-setup-postgresql
    state=present

- name: Install Spacewalk-Postgresql
  yum:
    name=spacewalk-postgresql
    state=present

- include_tasks: firewall.yml

- name: Create /var/tmp/answers directory
  file:
    path=/var/tmp/answers
    state=directory

- name: Copy Spacewalk answer file to /var/tmp/answers
  template:
    src=answers.j2
    dest=/var/tmp/answers/
    owner=root
    group=root
    mode=0600

- name: Install Spacewalk
  command: spacewalk-setup --answer-file=/var/tmp/answers/answers.j2

- name: Delete /var/tmp/answers directory
  file: path=/var/tmp/answers state=absent
