---
# tasks file for database

- name: Install mariadb
  yum: name={{ items }} state=latest
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python
    - php-mysql

- name: Ensure MariaDB is properly configured
  template:
    src: etc_my.cnf.d_network.cnf.j2
    dest: /etc/my.cnf.d/network.cnf

- name: start and enable mariadb
  service:
    name: mariadb
    enabled: yes
    state: started

- name: Create the database
  mysql_db:
    name: '{{ dbname }}'
    encoding: utf8
    state: present

- name: Create user and perms.
  mysql_user:
    name: '{{ dbuser }}'
    state: present
    host: '%'
    password: '{{ dbpass }}'
    priv: '*.*:ALL'
