---
# tasks file for database

- name: Install mariadb
  yum: name={{ item }} state=latest
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python
    - php-mysql

- name: Start and enable MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes

#- include_tasks: mysql-secure.yml

#- include: centos.yml
#  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 6
#
#- include: ubuntu.yml
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= '16.04'
