---
    # tasks file for common

#- name: add https to firewall
#  firewalld:
#    service: https
#    permanent: yes
#    state: enabled

- include: firewalld.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  
- include: motd.yml