---
- name: Install NTP
  yum:
    name: ntp
    state: latest

- name: Configure NTP file
  template:
    src=../templates/ntp.conf.j2
    dest=/etc/ntp.conf

- name: Start the NTP service
  service:
    name: ntpd
    state: started
    enabled: yes